[package]
name = "ink"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.9.7", package = "gtk4"}
gtk4-layer-shell = "0.5.0"
glib = "0.21.3"
gio = "0.20.12"
cairo-rs = "0.20.12"
pango = "0.20.12"
rsass = "0.29.2"
mlua = { version = "0.11.4", features = ["lua54", "vendored"] }
clap = { version = "4.0", features = ["derive"] }
once_cell = "1.18"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] } 
